// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"context"
	"time"

	"github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/telemetry"
	"go.microcore.dev/framework/transport/kafka/reader"
	"go.microcore.dev/framework/transport/kafka/writer"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// GetShutdownHandler provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownHandler() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownHandler")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_GetShutdownHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownHandler'
type MockManager_GetShutdownHandler_Call struct {
	*mock.Call
}

// GetShutdownHandler is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownHandler() *MockManager_GetShutdownHandler_Call {
	return &MockManager_GetShutdownHandler_Call{Call: _e.mock.On("GetShutdownHandler")}
}

func (_c *MockManager_GetShutdownHandler_Call) Run(run func()) *MockManager_GetShutdownHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) Return(b bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) RunAndReturn(run func() bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(run)
	return _c
}

// GetShutdownTimeout provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockManager_GetShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownTimeout'
type MockManager_GetShutdownTimeout_Call struct {
	*mock.Call
}

// GetShutdownTimeout is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownTimeout() *MockManager_GetShutdownTimeout_Call {
	return &MockManager_GetShutdownTimeout_Call{Call: _e.mock.On("GetShutdownTimeout")}
}

func (_c *MockManager_GetShutdownTimeout_Call) Run(run func()) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) Return(duration time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) RunAndReturn(run func() time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// GetTelemetryManager provides a mock function for the type MockManager
func (_mock *MockManager) GetTelemetryManager() telemetry.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTelemetryManager")
	}

	var r0 telemetry.Manager
	if returnFunc, ok := ret.Get(0).(func() telemetry.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telemetry.Manager)
		}
	}
	return r0
}

// MockManager_GetTelemetryManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTelemetryManager'
type MockManager_GetTelemetryManager_Call struct {
	*mock.Call
}

// GetTelemetryManager is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetTelemetryManager() *MockManager_GetTelemetryManager_Call {
	return &MockManager_GetTelemetryManager_Call{Call: _e.mock.On("GetTelemetryManager")}
}

func (_c *MockManager_GetTelemetryManager_Call) Run(run func()) *MockManager_GetTelemetryManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetTelemetryManager_Call) Return(manager telemetry.Manager) *MockManager_GetTelemetryManager_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_GetTelemetryManager_Call) RunAndReturn(run func() telemetry.Manager) *MockManager_GetTelemetryManager_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopicReader provides a mock function for the type MockManager
func (_mock *MockManager) GetTopicReader(topic string) *kafka.Reader {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for GetTopicReader")
	}

	var r0 *kafka.Reader
	if returnFunc, ok := ret.Get(0).(func(string) *kafka.Reader); ok {
		r0 = returnFunc(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.Reader)
		}
	}
	return r0
}

// MockManager_GetTopicReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopicReader'
type MockManager_GetTopicReader_Call struct {
	*mock.Call
}

// GetTopicReader is a helper method to define mock.On call
//   - topic string
func (_e *MockManager_Expecter) GetTopicReader(topic interface{}) *MockManager_GetTopicReader_Call {
	return &MockManager_GetTopicReader_Call{Call: _e.mock.On("GetTopicReader", topic)}
}

func (_c *MockManager_GetTopicReader_Call) Run(run func(topic string)) *MockManager_GetTopicReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GetTopicReader_Call) Return(reader *kafka.Reader) *MockManager_GetTopicReader_Call {
	_c.Call.Return(reader)
	return _c
}

func (_c *MockManager_GetTopicReader_Call) RunAndReturn(run func(topic string) *kafka.Reader) *MockManager_GetTopicReader_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopicWriter provides a mock function for the type MockManager
func (_mock *MockManager) GetTopicWriter(topic string) *kafka.Writer {
	ret := _mock.Called(topic)

	if len(ret) == 0 {
		panic("no return value specified for GetTopicWriter")
	}

	var r0 *kafka.Writer
	if returnFunc, ok := ret.Get(0).(func(string) *kafka.Writer); ok {
		r0 = returnFunc(topic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kafka.Writer)
		}
	}
	return r0
}

// MockManager_GetTopicWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopicWriter'
type MockManager_GetTopicWriter_Call struct {
	*mock.Call
}

// GetTopicWriter is a helper method to define mock.On call
//   - topic string
func (_e *MockManager_Expecter) GetTopicWriter(topic interface{}) *MockManager_GetTopicWriter_Call {
	return &MockManager_GetTopicWriter_Call{Call: _e.mock.On("GetTopicWriter", topic)}
}

func (_c *MockManager_GetTopicWriter_Call) Run(run func(topic string)) *MockManager_GetTopicWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_GetTopicWriter_Call) Return(writer *kafka.Writer) *MockManager_GetTopicWriter_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockManager_GetTopicWriter_Call) RunAndReturn(run func(topic string) *kafka.Writer) *MockManager_GetTopicWriter_Call {
	_c.Call.Return(run)
	return _c
}

// NewTopicReader provides a mock function for the type MockManager
func (_mock *MockManager) NewTopicReader(topic string, opts ...reader.Option) Manager {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(topic, opts)
	} else {
		tmpRet = _mock.Called(topic)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for NewTopicReader")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(string, ...reader.Option) Manager); ok {
		r0 = returnFunc(topic, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_NewTopicReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTopicReader'
type MockManager_NewTopicReader_Call struct {
	*mock.Call
}

// NewTopicReader is a helper method to define mock.On call
//   - topic string
//   - opts ...reader.Option
func (_e *MockManager_Expecter) NewTopicReader(topic interface{}, opts ...interface{}) *MockManager_NewTopicReader_Call {
	return &MockManager_NewTopicReader_Call{Call: _e.mock.On("NewTopicReader",
		append([]interface{}{topic}, opts...)...)}
}

func (_c *MockManager_NewTopicReader_Call) Run(run func(topic string, opts ...reader.Option)) *MockManager_NewTopicReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []reader.Option
		var variadicArgs []reader.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]reader.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockManager_NewTopicReader_Call) Return(manager Manager) *MockManager_NewTopicReader_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_NewTopicReader_Call) RunAndReturn(run func(topic string, opts ...reader.Option) Manager) *MockManager_NewTopicReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewTopicWriter provides a mock function for the type MockManager
func (_mock *MockManager) NewTopicWriter(topic string, opts ...writer.Option) Manager {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(topic, opts)
	} else {
		tmpRet = _mock.Called(topic)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for NewTopicWriter")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(string, ...writer.Option) Manager); ok {
		r0 = returnFunc(topic, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_NewTopicWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewTopicWriter'
type MockManager_NewTopicWriter_Call struct {
	*mock.Call
}

// NewTopicWriter is a helper method to define mock.On call
//   - topic string
//   - opts ...writer.Option
func (_e *MockManager_Expecter) NewTopicWriter(topic interface{}, opts ...interface{}) *MockManager_NewTopicWriter_Call {
	return &MockManager_NewTopicWriter_Call{Call: _e.mock.On("NewTopicWriter",
		append([]interface{}{topic}, opts...)...)}
}

func (_c *MockManager_NewTopicWriter_Call) Run(run func(topic string, opts ...writer.Option)) *MockManager_NewTopicWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []writer.Option
		var variadicArgs []writer.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]writer.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockManager_NewTopicWriter_Call) Return(manager Manager) *MockManager_NewTopicWriter_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_NewTopicWriter_Call) RunAndReturn(run func(topic string, opts ...writer.Option) Manager) *MockManager_NewTopicWriter_Call {
	_c.Call.Return(run)
	return _c
}

// Pub provides a mock function for the type MockManager
func (_mock *MockManager) Pub(topic string, payload []byte, opts ...PubOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(topic, payload, opts)
	} else {
		tmpRet = _mock.Called(topic, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Pub")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...PubOption) error); ok {
		r0 = returnFunc(topic, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Pub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pub'
type MockManager_Pub_Call struct {
	*mock.Call
}

// Pub is a helper method to define mock.On call
//   - topic string
//   - payload []byte
//   - opts ...PubOption
func (_e *MockManager_Expecter) Pub(topic interface{}, payload interface{}, opts ...interface{}) *MockManager_Pub_Call {
	return &MockManager_Pub_Call{Call: _e.mock.On("Pub",
		append([]interface{}{topic, payload}, opts...)...)}
}

func (_c *MockManager_Pub_Call) Run(run func(topic string, payload []byte, opts ...PubOption)) *MockManager_Pub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []PubOption
		var variadicArgs []PubOption
		if len(args) > 2 {
			variadicArgs = args[2].([]PubOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManager_Pub_Call) Return(err error) *MockManager_Pub_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Pub_Call) RunAndReturn(run func(topic string, payload []byte, opts ...PubOption) error) *MockManager_Pub_Call {
	_c.Call.Return(run)
	return _c
}

// PubJson provides a mock function for the type MockManager
func (_mock *MockManager) PubJson(topic string, payload any, opts ...PubOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(topic, payload, opts)
	} else {
		tmpRet = _mock.Called(topic, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PubJson")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, any, ...PubOption) error); ok {
		r0 = returnFunc(topic, payload, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_PubJson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PubJson'
type MockManager_PubJson_Call struct {
	*mock.Call
}

// PubJson is a helper method to define mock.On call
//   - topic string
//   - payload any
//   - opts ...PubOption
func (_e *MockManager_Expecter) PubJson(topic interface{}, payload interface{}, opts ...interface{}) *MockManager_PubJson_Call {
	return &MockManager_PubJson_Call{Call: _e.mock.On("PubJson",
		append([]interface{}{topic, payload}, opts...)...)}
}

func (_c *MockManager_PubJson_Call) Run(run func(topic string, payload any, opts ...PubOption)) *MockManager_PubJson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 []PubOption
		var variadicArgs []PubOption
		if len(args) > 2 {
			variadicArgs = args[2].([]PubOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManager_PubJson_Call) Return(err error) *MockManager_PubJson_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_PubJson_Call) RunAndReturn(run func(topic string, payload any, opts ...PubOption) error) *MockManager_PubJson_Call {
	_c.Call.Return(run)
	return _c
}

// SetTelemetryManager provides a mock function for the type MockManager
func (_mock *MockManager) SetTelemetryManager(telemetry1 telemetry.Manager) Manager {
	ret := _mock.Called(telemetry1)

	if len(ret) == 0 {
		panic("no return value specified for SetTelemetryManager")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(telemetry.Manager) Manager); ok {
		r0 = returnFunc(telemetry1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetTelemetryManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTelemetryManager'
type MockManager_SetTelemetryManager_Call struct {
	*mock.Call
}

// SetTelemetryManager is a helper method to define mock.On call
//   - telemetry1 telemetry.Manager
func (_e *MockManager_Expecter) SetTelemetryManager(telemetry1 interface{}) *MockManager_SetTelemetryManager_Call {
	return &MockManager_SetTelemetryManager_Call{Call: _e.mock.On("SetTelemetryManager", telemetry1)}
}

func (_c *MockManager_SetTelemetryManager_Call) Run(run func(telemetry1 telemetry.Manager)) *MockManager_SetTelemetryManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telemetry.Manager
		if args[0] != nil {
			arg0 = args[0].(telemetry.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) Return(manager Manager) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) RunAndReturn(run func(telemetry1 telemetry.Manager) Manager) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(run)
	return _c
}

// SetTopicReader provides a mock function for the type MockManager
func (_mock *MockManager) SetTopicReader(topic string, reader1 *kafka.Reader) Manager {
	ret := _mock.Called(topic, reader1)

	if len(ret) == 0 {
		panic("no return value specified for SetTopicReader")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(string, *kafka.Reader) Manager); ok {
		r0 = returnFunc(topic, reader1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetTopicReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTopicReader'
type MockManager_SetTopicReader_Call struct {
	*mock.Call
}

// SetTopicReader is a helper method to define mock.On call
//   - topic string
//   - reader1 *kafka.Reader
func (_e *MockManager_Expecter) SetTopicReader(topic interface{}, reader1 interface{}) *MockManager_SetTopicReader_Call {
	return &MockManager_SetTopicReader_Call{Call: _e.mock.On("SetTopicReader", topic, reader1)}
}

func (_c *MockManager_SetTopicReader_Call) Run(run func(topic string, reader1 *kafka.Reader)) *MockManager_SetTopicReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *kafka.Reader
		if args[1] != nil {
			arg1 = args[1].(*kafka.Reader)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_SetTopicReader_Call) Return(manager Manager) *MockManager_SetTopicReader_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetTopicReader_Call) RunAndReturn(run func(topic string, reader1 *kafka.Reader) Manager) *MockManager_SetTopicReader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTopicWriter provides a mock function for the type MockManager
func (_mock *MockManager) SetTopicWriter(topic string, writer1 *kafka.Writer) Manager {
	ret := _mock.Called(topic, writer1)

	if len(ret) == 0 {
		panic("no return value specified for SetTopicWriter")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(string, *kafka.Writer) Manager); ok {
		r0 = returnFunc(topic, writer1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetTopicWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTopicWriter'
type MockManager_SetTopicWriter_Call struct {
	*mock.Call
}

// SetTopicWriter is a helper method to define mock.On call
//   - topic string
//   - writer1 *kafka.Writer
func (_e *MockManager_Expecter) SetTopicWriter(topic interface{}, writer1 interface{}) *MockManager_SetTopicWriter_Call {
	return &MockManager_SetTopicWriter_Call{Call: _e.mock.On("SetTopicWriter", topic, writer1)}
}

func (_c *MockManager_SetTopicWriter_Call) Run(run func(topic string, writer1 *kafka.Writer)) *MockManager_SetTopicWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *kafka.Writer
		if args[1] != nil {
			arg1 = args[1].(*kafka.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_SetTopicWriter_Call) Return(manager Manager) *MockManager_SetTopicWriter_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetTopicWriter_Call) RunAndReturn(run func(topic string, writer1 *kafka.Writer) Manager) *MockManager_SetTopicWriter_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockManager
func (_mock *MockManager) Shutdown(ctx context.Context, code int) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockManager_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - code int
func (_e *MockManager_Expecter) Shutdown(ctx interface{}, code interface{}) *MockManager_Shutdown_Call {
	return &MockManager_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx, code)}
}

func (_c *MockManager_Shutdown_Call) Run(run func(ctx context.Context, code int)) *MockManager_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Shutdown_Call) Return(err error) *MockManager_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Shutdown_Call) RunAndReturn(run func(ctx context.Context, code int) error) *MockManager_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Sub provides a mock function for the type MockManager
func (_mock *MockManager) Sub(topic string, opts ...SubOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(topic, opts)
	} else {
		tmpRet = _mock.Called(topic)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Sub")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...SubOption) error); ok {
		r0 = returnFunc(topic, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Sub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sub'
type MockManager_Sub_Call struct {
	*mock.Call
}

// Sub is a helper method to define mock.On call
//   - topic string
//   - opts ...SubOption
func (_e *MockManager_Expecter) Sub(topic interface{}, opts ...interface{}) *MockManager_Sub_Call {
	return &MockManager_Sub_Call{Call: _e.mock.On("Sub",
		append([]interface{}{topic}, opts...)...)}
}

func (_c *MockManager_Sub_Call) Run(run func(topic string, opts ...SubOption)) *MockManager_Sub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []SubOption
		var variadicArgs []SubOption
		if len(args) > 1 {
			variadicArgs = args[1].([]SubOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockManager_Sub_Call) Return(err error) *MockManager_Sub_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Sub_Call) RunAndReturn(run func(topic string, opts ...SubOption) error) *MockManager_Sub_Call {
	_c.Call.Return(run)
	return _c
}
