// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	mock "github.com/stretchr/testify/mock"
	"github.com/valyala/fasthttp"
	"go.microcore.dev/framework/telemetry"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Request provides a mock function for the type MockManager
func (_mock *MockManager) Request(url string, opts ...RequestOption) (*response, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(url, opts)
	} else {
		tmpRet = _mock.Called(url)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 *response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...RequestOption) (*response, error)); ok {
		return returnFunc(url, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...RequestOption) *response); ok {
		r0 = returnFunc(url, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...RequestOption) error); ok {
		r1 = returnFunc(url, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type MockManager_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - url string
//   - opts ...RequestOption
func (_e *MockManager_Expecter) Request(url interface{}, opts ...interface{}) *MockManager_Request_Call {
	return &MockManager_Request_Call{Call: _e.mock.On("Request",
		append([]interface{}{url}, opts...)...)}
}

func (_c *MockManager_Request_Call) Run(run func(url string, opts ...RequestOption)) *MockManager_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []RequestOption
		var variadicArgs []RequestOption
		if len(args) > 1 {
			variadicArgs = args[1].([]RequestOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockManager_Request_Call) Return(responseMoqParam *response, err error) *MockManager_Request_Call {
	_c.Call.Return(responseMoqParam, err)
	return _c
}

func (_c *MockManager_Request_Call) RunAndReturn(run func(url string, opts ...RequestOption) (*response, error)) *MockManager_Request_Call {
	_c.Call.Return(run)
	return _c
}

// SetCore provides a mock function for the type MockManager
func (_mock *MockManager) SetCore(core *fasthttp.Client) Manager {
	ret := _mock.Called(core)

	if len(ret) == 0 {
		panic("no return value specified for SetCore")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(*fasthttp.Client) Manager); ok {
		r0 = returnFunc(core)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetCore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCore'
type MockManager_SetCore_Call struct {
	*mock.Call
}

// SetCore is a helper method to define mock.On call
//   - core *fasthttp.Client
func (_e *MockManager_Expecter) SetCore(core interface{}) *MockManager_SetCore_Call {
	return &MockManager_SetCore_Call{Call: _e.mock.On("SetCore", core)}
}

func (_c *MockManager_SetCore_Call) Run(run func(core *fasthttp.Client)) *MockManager_SetCore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fasthttp.Client
		if args[0] != nil {
			arg0 = args[0].(*fasthttp.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetCore_Call) Return(manager Manager) *MockManager_SetCore_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetCore_Call) RunAndReturn(run func(core *fasthttp.Client) Manager) *MockManager_SetCore_Call {
	_c.Call.Return(run)
	return _c
}

// SetTelemetryManager provides a mock function for the type MockManager
func (_mock *MockManager) SetTelemetryManager(telemetry1 telemetry.Manager) Manager {
	ret := _mock.Called(telemetry1)

	if len(ret) == 0 {
		panic("no return value specified for SetTelemetryManager")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(telemetry.Manager) Manager); ok {
		r0 = returnFunc(telemetry1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetTelemetryManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTelemetryManager'
type MockManager_SetTelemetryManager_Call struct {
	*mock.Call
}

// SetTelemetryManager is a helper method to define mock.On call
//   - telemetry1 telemetry.Manager
func (_e *MockManager_Expecter) SetTelemetryManager(telemetry1 interface{}) *MockManager_SetTelemetryManager_Call {
	return &MockManager_SetTelemetryManager_Call{Call: _e.mock.On("SetTelemetryManager", telemetry1)}
}

func (_c *MockManager_SetTelemetryManager_Call) Run(run func(telemetry1 telemetry.Manager)) *MockManager_SetTelemetryManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telemetry.Manager
		if args[0] != nil {
			arg0 = args[0].(telemetry.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) Return(manager Manager) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) RunAndReturn(run func(telemetry1 telemetry.Manager) Manager) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(run)
	return _c
}
