// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shutdown

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// AddHandler provides a mock function for the type MockManager
func (_mock *MockManager) AddHandler(handler Handler) error {
	ret := _mock.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for AddHandler")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Handler) error); ok {
		r0 = returnFunc(handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_AddHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHandler'
type MockManager_AddHandler_Call struct {
	*mock.Call
}

// AddHandler is a helper method to define mock.On call
//   - handler Handler
func (_e *MockManager_Expecter) AddHandler(handler interface{}) *MockManager_AddHandler_Call {
	return &MockManager_AddHandler_Call{Call: _e.mock.On("AddHandler", handler)}
}

func (_c *MockManager_AddHandler_Call) Run(run func(handler Handler)) *MockManager_AddHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Handler
		if args[0] != nil {
			arg0 = args[0].(Handler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_AddHandler_Call) Return(err error) *MockManager_AddHandler_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_AddHandler_Call) RunAndReturn(run func(handler Handler) error) *MockManager_AddHandler_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockManager
func (_mock *MockManager) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockManager_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockManager_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockManager_Expecter) Context() *MockManager_Context_Call {
	return &MockManager_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockManager_Context_Call) Run(run func()) *MockManager_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Context_Call) Return(context1 context.Context) *MockManager_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockManager_Context_Call) RunAndReturn(run func() context.Context) *MockManager_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Exit provides a mock function for the type MockManager
func (_mock *MockManager) Exit(code int) {
	_mock.Called(code)
	return
}

// MockManager_Exit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exit'
type MockManager_Exit_Call struct {
	*mock.Call
}

// Exit is a helper method to define mock.On call
//   - code int
func (_e *MockManager_Expecter) Exit(code interface{}) *MockManager_Exit_Call {
	return &MockManager_Exit_Call{Call: _e.mock.On("Exit", code)}
}

func (_c *MockManager_Exit_Call) Run(run func(code int)) *MockManager_Exit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_Exit_Call) Return() *MockManager_Exit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Exit_Call) RunAndReturn(run func(code int)) *MockManager_Exit_Call {
	_c.Run(run)
	return _c
}

// NewContext provides a mock function for the type MockManager
func (_mock *MockManager) NewContext() (context.Context, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewContext")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (context.Context, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_NewContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewContext'
type MockManager_NewContext_Call struct {
	*mock.Call
}

// NewContext is a helper method to define mock.On call
func (_e *MockManager_Expecter) NewContext() *MockManager_NewContext_Call {
	return &MockManager_NewContext_Call{Call: _e.mock.On("NewContext")}
}

func (_c *MockManager_NewContext_Call) Run(run func()) *MockManager_NewContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_NewContext_Call) Return(context1 context.Context, err error) *MockManager_NewContext_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *MockManager_NewContext_Call) RunAndReturn(run func() (context.Context, error)) *MockManager_NewContext_Call {
	_c.Call.Return(run)
	return _c
}

// Recover provides a mock function for the type MockManager
func (_mock *MockManager) Recover() {
	_mock.Called()
	return
}

// MockManager_Recover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recover'
type MockManager_Recover_Call struct {
	*mock.Call
}

// Recover is a helper method to define mock.On call
func (_e *MockManager_Expecter) Recover() *MockManager_Recover_Call {
	return &MockManager_Recover_Call{Call: _e.mock.On("Recover")}
}

func (_c *MockManager_Recover_Call) Run(run func()) *MockManager_Recover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Recover_Call) Return() *MockManager_Recover_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Recover_Call) RunAndReturn(run func()) *MockManager_Recover_Call {
	_c.Run(run)
	return _c
}

// SetShutdownTimeout provides a mock function for the type MockManager
func (_mock *MockManager) SetShutdownTimeout(t time.Duration) {
	_mock.Called(t)
	return
}

// MockManager_SetShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShutdownTimeout'
type MockManager_SetShutdownTimeout_Call struct {
	*mock.Call
}

// SetShutdownTimeout is a helper method to define mock.On call
//   - t time.Duration
func (_e *MockManager_Expecter) SetShutdownTimeout(t interface{}) *MockManager_SetShutdownTimeout_Call {
	return &MockManager_SetShutdownTimeout_Call{Call: _e.mock.On("SetShutdownTimeout", t)}
}

func (_c *MockManager_SetShutdownTimeout_Call) Run(run func(t time.Duration)) *MockManager_SetShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetShutdownTimeout_Call) Return() *MockManager_SetShutdownTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SetShutdownTimeout_Call) RunAndReturn(run func(t time.Duration)) *MockManager_SetShutdownTimeout_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockManager
func (_mock *MockManager) Shutdown(code int) {
	_mock.Called(code)
	return
}

// MockManager_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockManager_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - code int
func (_e *MockManager_Expecter) Shutdown(code interface{}) *MockManager_Shutdown_Call {
	return &MockManager_Shutdown_Call{Call: _e.mock.On("Shutdown", code)}
}

func (_c *MockManager_Shutdown_Call) Run(run func(code int)) *MockManager_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_Shutdown_Call) Return() *MockManager_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Shutdown_Call) RunAndReturn(run func(code int)) *MockManager_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Wait provides a mock function for the type MockManager
func (_mock *MockManager) Wait() {
	_mock.Called()
	return
}

// MockManager_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockManager_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
func (_e *MockManager_Expecter) Wait() *MockManager_Wait_Call {
	return &MockManager_Wait_Call{Call: _e.mock.On("Wait")}
}

func (_c *MockManager_Wait_Call) Run(run func()) *MockManager_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Wait_Call) Return() *MockManager_Wait_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Wait_Call) RunAndReturn(run func()) *MockManager_Wait_Call {
	_c.Run(run)
	return _c
}

// WithContext provides a mock function for the type MockManager
func (_mock *MockManager) WithContext(parent context.Context) (context.Context, error) {
	ret := _mock.Called(parent)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (context.Context, error)); ok {
		return returnFunc(parent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(parent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(parent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type MockManager_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - parent context.Context
func (_e *MockManager_Expecter) WithContext(parent interface{}) *MockManager_WithContext_Call {
	return &MockManager_WithContext_Call{Call: _e.mock.On("WithContext", parent)}
}

func (_c *MockManager_WithContext_Call) Run(run func(parent context.Context)) *MockManager_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_WithContext_Call) Return(context1 context.Context, err error) *MockManager_WithContext_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *MockManager_WithContext_Call) RunAndReturn(run func(parent context.Context) (context.Context, error)) *MockManager_WithContext_Call {
	_c.Call.Return(run)
	return _c
}
