// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	"context"
	"net"
	"time"

	"github.com/fasthttp/router"
	mock "github.com/stretchr/testify/mock"
	"github.com/valyala/fasthttp"
	"go.microcore.dev/framework/telemetry"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// AddMiddleware provides a mock function for the type MockManager
func (_mock *MockManager) AddMiddleware(middlewareHandler MiddlewareHandler) Manager {
	ret := _mock.Called(middlewareHandler)

	if len(ret) == 0 {
		panic("no return value specified for AddMiddleware")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(MiddlewareHandler) Manager); ok {
		r0 = returnFunc(middlewareHandler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_AddMiddleware_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMiddleware'
type MockManager_AddMiddleware_Call struct {
	*mock.Call
}

// AddMiddleware is a helper method to define mock.On call
//   - middlewareHandler MiddlewareHandler
func (_e *MockManager_Expecter) AddMiddleware(middlewareHandler interface{}) *MockManager_AddMiddleware_Call {
	return &MockManager_AddMiddleware_Call{Call: _e.mock.On("AddMiddleware", middlewareHandler)}
}

func (_c *MockManager_AddMiddleware_Call) Run(run func(middlewareHandler MiddlewareHandler)) *MockManager_AddMiddleware_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 MiddlewareHandler
		if args[0] != nil {
			arg0 = args[0].(MiddlewareHandler)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_AddMiddleware_Call) Return(manager Manager) *MockManager_AddMiddleware_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_AddMiddleware_Call) RunAndReturn(run func(middlewareHandler MiddlewareHandler) Manager) *MockManager_AddMiddleware_Call {
	_c.Call.Return(run)
	return _c
}

// AddRoute provides a mock function for the type MockManager
func (_mock *MockManager) AddRoute(opts ...RouteOption) Manager {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddRoute")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(...RouteOption) Manager); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_AddRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoute'
type MockManager_AddRoute_Call struct {
	*mock.Call
}

// AddRoute is a helper method to define mock.On call
//   - opts ...RouteOption
func (_e *MockManager_Expecter) AddRoute(opts ...interface{}) *MockManager_AddRoute_Call {
	return &MockManager_AddRoute_Call{Call: _e.mock.On("AddRoute",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockManager_AddRoute_Call) Run(run func(opts ...RouteOption)) *MockManager_AddRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []RouteOption
		var variadicArgs []RouteOption
		if len(args) > 0 {
			variadicArgs = args[0].([]RouteOption)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockManager_AddRoute_Call) Return(manager Manager) *MockManager_AddRoute_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_AddRoute_Call) RunAndReturn(run func(opts ...RouteOption) Manager) *MockManager_AddRoute_Call {
	_c.Call.Return(run)
	return _c
}

// AddRouteGroup provides a mock function for the type MockManager
func (_mock *MockManager) AddRouteGroup(opts ...RouteGroupOption) Manager {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddRouteGroup")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(...RouteGroupOption) Manager); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_AddRouteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRouteGroup'
type MockManager_AddRouteGroup_Call struct {
	*mock.Call
}

// AddRouteGroup is a helper method to define mock.On call
//   - opts ...RouteGroupOption
func (_e *MockManager_Expecter) AddRouteGroup(opts ...interface{}) *MockManager_AddRouteGroup_Call {
	return &MockManager_AddRouteGroup_Call{Call: _e.mock.On("AddRouteGroup",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockManager_AddRouteGroup_Call) Run(run func(opts ...RouteGroupOption)) *MockManager_AddRouteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []RouteGroupOption
		var variadicArgs []RouteGroupOption
		if len(args) > 0 {
			variadicArgs = args[0].([]RouteGroupOption)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockManager_AddRouteGroup_Call) Return(manager Manager) *MockManager_AddRouteGroup_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_AddRouteGroup_Call) RunAndReturn(run func(opts ...RouteGroupOption) Manager) *MockManager_AddRouteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// EnableTLS provides a mock function for the type MockManager
func (_mock *MockManager) EnableTLS(tls *TLS) Manager {
	ret := _mock.Called(tls)

	if len(ret) == 0 {
		panic("no return value specified for EnableTLS")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(*TLS) Manager); ok {
		r0 = returnFunc(tls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_EnableTLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableTLS'
type MockManager_EnableTLS_Call struct {
	*mock.Call
}

// EnableTLS is a helper method to define mock.On call
//   - tls *TLS
func (_e *MockManager_Expecter) EnableTLS(tls interface{}) *MockManager_EnableTLS_Call {
	return &MockManager_EnableTLS_Call{Call: _e.mock.On("EnableTLS", tls)}
}

func (_c *MockManager_EnableTLS_Call) Run(run func(tls *TLS)) *MockManager_EnableTLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *TLS
		if args[0] != nil {
			arg0 = args[0].(*TLS)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_EnableTLS_Call) Return(manager Manager) *MockManager_EnableTLS_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_EnableTLS_Call) RunAndReturn(run func(tls *TLS) Manager) *MockManager_EnableTLS_Call {
	_c.Call.Return(run)
	return _c
}

// GetShutdownHandler provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownHandler() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownHandler")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_GetShutdownHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownHandler'
type MockManager_GetShutdownHandler_Call struct {
	*mock.Call
}

// GetShutdownHandler is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownHandler() *MockManager_GetShutdownHandler_Call {
	return &MockManager_GetShutdownHandler_Call{Call: _e.mock.On("GetShutdownHandler")}
}

func (_c *MockManager_GetShutdownHandler_Call) Run(run func()) *MockManager_GetShutdownHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) Return(b bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) RunAndReturn(run func() bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(run)
	return _c
}

// GetShutdownTimeout provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockManager_GetShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownTimeout'
type MockManager_GetShutdownTimeout_Call struct {
	*mock.Call
}

// GetShutdownTimeout is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownTimeout() *MockManager_GetShutdownTimeout_Call {
	return &MockManager_GetShutdownTimeout_Call{Call: _e.mock.On("GetShutdownTimeout")}
}

func (_c *MockManager_GetShutdownTimeout_Call) Run(run func()) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) Return(duration time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) RunAndReturn(run func() time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// Listen provides a mock function for the type MockManager
func (_mock *MockManager) Listen() <-chan error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Listen")
	}

	var r0 <-chan error
	if returnFunc, ok := ret.Get(0).(func() <-chan error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan error)
		}
	}
	return r0
}

// MockManager_Listen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Listen'
type MockManager_Listen_Call struct {
	*mock.Call
}

// Listen is a helper method to define mock.On call
func (_e *MockManager_Expecter) Listen() *MockManager_Listen_Call {
	return &MockManager_Listen_Call{Call: _e.mock.On("Listen")}
}

func (_c *MockManager_Listen_Call) Run(run func()) *MockManager_Listen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Listen_Call) Return(errCh <-chan error) *MockManager_Listen_Call {
	_c.Call.Return(errCh)
	return _c
}

func (_c *MockManager_Listen_Call) RunAndReturn(run func() <-chan error) *MockManager_Listen_Call {
	_c.Call.Return(run)
	return _c
}

// SetCore provides a mock function for the type MockManager
func (_mock *MockManager) SetCore(core *fasthttp.Server) Manager {
	ret := _mock.Called(core)

	if len(ret) == 0 {
		panic("no return value specified for SetCore")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(*fasthttp.Server) Manager); ok {
		r0 = returnFunc(core)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetCore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCore'
type MockManager_SetCore_Call struct {
	*mock.Call
}

// SetCore is a helper method to define mock.On call
//   - core *fasthttp.Server
func (_e *MockManager_Expecter) SetCore(core interface{}) *MockManager_SetCore_Call {
	return &MockManager_SetCore_Call{Call: _e.mock.On("SetCore", core)}
}

func (_c *MockManager_SetCore_Call) Run(run func(core *fasthttp.Server)) *MockManager_SetCore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fasthttp.Server
		if args[0] != nil {
			arg0 = args[0].(*fasthttp.Server)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetCore_Call) Return(manager Manager) *MockManager_SetCore_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetCore_Call) RunAndReturn(run func(core *fasthttp.Server) Manager) *MockManager_SetCore_Call {
	_c.Call.Return(run)
	return _c
}

// SetListener provides a mock function for the type MockManager
func (_mock *MockManager) SetListener(listener net.Listener) Manager {
	ret := _mock.Called(listener)

	if len(ret) == 0 {
		panic("no return value specified for SetListener")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(net.Listener) Manager); ok {
		r0 = returnFunc(listener)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetListener'
type MockManager_SetListener_Call struct {
	*mock.Call
}

// SetListener is a helper method to define mock.On call
//   - listener net.Listener
func (_e *MockManager_Expecter) SetListener(listener interface{}) *MockManager_SetListener_Call {
	return &MockManager_SetListener_Call{Call: _e.mock.On("SetListener", listener)}
}

func (_c *MockManager_SetListener_Call) Run(run func(listener net.Listener)) *MockManager_SetListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Listener
		if args[0] != nil {
			arg0 = args[0].(net.Listener)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetListener_Call) Return(manager Manager) *MockManager_SetListener_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetListener_Call) RunAndReturn(run func(listener net.Listener) Manager) *MockManager_SetListener_Call {
	_c.Call.Return(run)
	return _c
}

// SetRouter provides a mock function for the type MockManager
func (_mock *MockManager) SetRouter(router1 *router.Router) Manager {
	ret := _mock.Called(router1)

	if len(ret) == 0 {
		panic("no return value specified for SetRouter")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(*router.Router) Manager); ok {
		r0 = returnFunc(router1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetRouter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRouter'
type MockManager_SetRouter_Call struct {
	*mock.Call
}

// SetRouter is a helper method to define mock.On call
//   - router1 *router.Router
func (_e *MockManager_Expecter) SetRouter(router1 interface{}) *MockManager_SetRouter_Call {
	return &MockManager_SetRouter_Call{Call: _e.mock.On("SetRouter", router1)}
}

func (_c *MockManager_SetRouter_Call) Run(run func(router1 *router.Router)) *MockManager_SetRouter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *router.Router
		if args[0] != nil {
			arg0 = args[0].(*router.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetRouter_Call) Return(manager Manager) *MockManager_SetRouter_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetRouter_Call) RunAndReturn(run func(router1 *router.Router) Manager) *MockManager_SetRouter_Call {
	_c.Call.Return(run)
	return _c
}

// SetTelemetryManager provides a mock function for the type MockManager
func (_mock *MockManager) SetTelemetryManager(telemetry1 telemetry.Manager) Manager {
	ret := _mock.Called(telemetry1)

	if len(ret) == 0 {
		panic("no return value specified for SetTelemetryManager")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(telemetry.Manager) Manager); ok {
		r0 = returnFunc(telemetry1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetTelemetryManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTelemetryManager'
type MockManager_SetTelemetryManager_Call struct {
	*mock.Call
}

// SetTelemetryManager is a helper method to define mock.On call
//   - telemetry1 telemetry.Manager
func (_e *MockManager_Expecter) SetTelemetryManager(telemetry1 interface{}) *MockManager_SetTelemetryManager_Call {
	return &MockManager_SetTelemetryManager_Call{Call: _e.mock.On("SetTelemetryManager", telemetry1)}
}

func (_c *MockManager_SetTelemetryManager_Call) Run(run func(telemetry1 telemetry.Manager)) *MockManager_SetTelemetryManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telemetry.Manager
		if args[0] != nil {
			arg0 = args[0].(telemetry.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) Return(manager Manager) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) RunAndReturn(run func(telemetry1 telemetry.Manager) Manager) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockManager
func (_mock *MockManager) Shutdown(ctx context.Context, code int) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockManager_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - code int
func (_e *MockManager_Expecter) Shutdown(ctx interface{}, code interface{}) *MockManager_Shutdown_Call {
	return &MockManager_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx, code)}
}

func (_c *MockManager_Shutdown_Call) Run(run func(ctx context.Context, code int)) *MockManager_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Shutdown_Call) Return(err error) *MockManager_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Shutdown_Call) RunAndReturn(run func(ctx context.Context, code int) error) *MockManager_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MockManager
func (_mock *MockManager) Up() {
	_mock.Called()
	return
}

// MockManager_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockManager_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
func (_e *MockManager_Expecter) Up() *MockManager_Up_Call {
	return &MockManager_Up_Call{Call: _e.mock.On("Up")}
}

func (_c *MockManager_Up_Call) Run(run func()) *MockManager_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Up_Call) Return() *MockManager_Up_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_Up_Call) RunAndReturn(run func()) *MockManager_Up_Call {
	_c.Run(run)
	return _c
}

// UseCors provides a mock function for the type MockManager
func (_mock *MockManager) UseCors(opts ...CorsOption) Manager {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UseCors")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(...CorsOption) Manager); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_UseCors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseCors'
type MockManager_UseCors_Call struct {
	*mock.Call
}

// UseCors is a helper method to define mock.On call
//   - opts ...CorsOption
func (_e *MockManager_Expecter) UseCors(opts ...interface{}) *MockManager_UseCors_Call {
	return &MockManager_UseCors_Call{Call: _e.mock.On("UseCors",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockManager_UseCors_Call) Run(run func(opts ...CorsOption)) *MockManager_UseCors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []CorsOption
		var variadicArgs []CorsOption
		if len(args) > 0 {
			variadicArgs = args[0].([]CorsOption)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockManager_UseCors_Call) Return(manager Manager) *MockManager_UseCors_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_UseCors_Call) RunAndReturn(run func(opts ...CorsOption) Manager) *MockManager_UseCors_Call {
	_c.Call.Return(run)
	return _c
}

// UseProfiling provides a mock function for the type MockManager
func (_mock *MockManager) UseProfiling() Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseProfiling")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func() Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_UseProfiling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseProfiling'
type MockManager_UseProfiling_Call struct {
	*mock.Call
}

// UseProfiling is a helper method to define mock.On call
func (_e *MockManager_Expecter) UseProfiling() *MockManager_UseProfiling_Call {
	return &MockManager_UseProfiling_Call{Call: _e.mock.On("UseProfiling")}
}

func (_c *MockManager_UseProfiling_Call) Run(run func()) *MockManager_UseProfiling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_UseProfiling_Call) Return(manager Manager) *MockManager_UseProfiling_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_UseProfiling_Call) RunAndReturn(run func() Manager) *MockManager_UseProfiling_Call {
	_c.Call.Return(run)
	return _c
}

// UseSwagger provides a mock function for the type MockManager
func (_mock *MockManager) UseSwagger() Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UseSwagger")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func() Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_UseSwagger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseSwagger'
type MockManager_UseSwagger_Call struct {
	*mock.Call
}

// UseSwagger is a helper method to define mock.On call
func (_e *MockManager_Expecter) UseSwagger() *MockManager_UseSwagger_Call {
	return &MockManager_UseSwagger_Call{Call: _e.mock.On("UseSwagger")}
}

func (_c *MockManager_UseSwagger_Call) Run(run func()) *MockManager_UseSwagger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_UseSwagger_Call) Return(manager Manager) *MockManager_UseSwagger_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_UseSwagger_Call) RunAndReturn(run func() Manager) *MockManager_UseSwagger_Call {
	_c.Call.Return(run)
	return _c
}
