// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package telemetry

import (
	"context"
	"net/http"
	"time"

	mock "github.com/stretchr/testify/mock"
	log0 "go.opentelemetry.io/otel/log"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/propagation"
	"go.opentelemetry.io/otel/sdk/log"
	metric0 "go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/trace"
	trace0 "go.opentelemetry.io/otel/trace"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// ForceFlush provides a mock function for the type MockManager
func (_mock *MockManager) ForceFlush(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ForceFlush")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_ForceFlush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceFlush'
type MockManager_ForceFlush_Call struct {
	*mock.Call
}

// ForceFlush is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) ForceFlush(ctx interface{}) *MockManager_ForceFlush_Call {
	return &MockManager_ForceFlush_Call{Call: _e.mock.On("ForceFlush", ctx)}
}

func (_c *MockManager_ForceFlush_Call) Run(run func(ctx context.Context)) *MockManager_ForceFlush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_ForceFlush_Call) Return(err error) *MockManager_ForceFlush_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_ForceFlush_Call) RunAndReturn(run func(ctx context.Context) error) *MockManager_ForceFlush_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogProvider provides a mock function for the type MockManager
func (_mock *MockManager) GetLogProvider() *log.LoggerProvider {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogProvider")
	}

	var r0 *log.LoggerProvider
	if returnFunc, ok := ret.Get(0).(func() *log.LoggerProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*log.LoggerProvider)
		}
	}
	return r0
}

// MockManager_GetLogProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogProvider'
type MockManager_GetLogProvider_Call struct {
	*mock.Call
}

// GetLogProvider is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetLogProvider() *MockManager_GetLogProvider_Call {
	return &MockManager_GetLogProvider_Call{Call: _e.mock.On("GetLogProvider")}
}

func (_c *MockManager_GetLogProvider_Call) Run(run func()) *MockManager_GetLogProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetLogProvider_Call) Return(loggerProvider *log.LoggerProvider) *MockManager_GetLogProvider_Call {
	_c.Call.Return(loggerProvider)
	return _c
}

func (_c *MockManager_GetLogProvider_Call) RunAndReturn(run func() *log.LoggerProvider) *MockManager_GetLogProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function for the type MockManager
func (_mock *MockManager) GetLogger() log0.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 log0.Logger
	if returnFunc, ok := ret.Get(0).(func() log0.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(log0.Logger)
		}
	}
	return r0
}

// MockManager_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockManager_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetLogger() *MockManager_GetLogger_Call {
	return &MockManager_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockManager_GetLogger_Call) Run(run func()) *MockManager_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetLogger_Call) Return(logger log0.Logger) *MockManager_GetLogger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockManager_GetLogger_Call) RunAndReturn(run func() log0.Logger) *MockManager_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeter provides a mock function for the type MockManager
func (_mock *MockManager) GetMeter() metric.Meter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMeter")
	}

	var r0 metric.Meter
	if returnFunc, ok := ret.Get(0).(func() metric.Meter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metric.Meter)
		}
	}
	return r0
}

// MockManager_GetMeter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeter'
type MockManager_GetMeter_Call struct {
	*mock.Call
}

// GetMeter is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetMeter() *MockManager_GetMeter_Call {
	return &MockManager_GetMeter_Call{Call: _e.mock.On("GetMeter")}
}

func (_c *MockManager_GetMeter_Call) Run(run func()) *MockManager_GetMeter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetMeter_Call) Return(meter metric.Meter) *MockManager_GetMeter_Call {
	_c.Call.Return(meter)
	return _c
}

func (_c *MockManager_GetMeter_Call) RunAndReturn(run func() metric.Meter) *MockManager_GetMeter_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetricProvider provides a mock function for the type MockManager
func (_mock *MockManager) GetMetricProvider() *metric0.MeterProvider {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetricProvider")
	}

	var r0 *metric0.MeterProvider
	if returnFunc, ok := ret.Get(0).(func() *metric0.MeterProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metric0.MeterProvider)
		}
	}
	return r0
}

// MockManager_GetMetricProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetricProvider'
type MockManager_GetMetricProvider_Call struct {
	*mock.Call
}

// GetMetricProvider is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetMetricProvider() *MockManager_GetMetricProvider_Call {
	return &MockManager_GetMetricProvider_Call{Call: _e.mock.On("GetMetricProvider")}
}

func (_c *MockManager_GetMetricProvider_Call) Run(run func()) *MockManager_GetMetricProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetMetricProvider_Call) Return(meterProvider *metric0.MeterProvider) *MockManager_GetMetricProvider_Call {
	_c.Call.Return(meterProvider)
	return _c
}

func (_c *MockManager_GetMetricProvider_Call) RunAndReturn(run func() *metric0.MeterProvider) *MockManager_GetMetricProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetricsHttpHandler provides a mock function for the type MockManager
func (_mock *MockManager) GetMetricsHttpHandler() http.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetricsHttpHandler")
	}

	var r0 http.Handler
	if returnFunc, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	return r0
}

// MockManager_GetMetricsHttpHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetricsHttpHandler'
type MockManager_GetMetricsHttpHandler_Call struct {
	*mock.Call
}

// GetMetricsHttpHandler is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetMetricsHttpHandler() *MockManager_GetMetricsHttpHandler_Call {
	return &MockManager_GetMetricsHttpHandler_Call{Call: _e.mock.On("GetMetricsHttpHandler")}
}

func (_c *MockManager_GetMetricsHttpHandler_Call) Run(run func()) *MockManager_GetMetricsHttpHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetMetricsHttpHandler_Call) Return(handler http.Handler) *MockManager_GetMetricsHttpHandler_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockManager_GetMetricsHttpHandler_Call) RunAndReturn(run func() http.Handler) *MockManager_GetMetricsHttpHandler_Call {
	_c.Call.Return(run)
	return _c
}

// GetPropagator provides a mock function for the type MockManager
func (_mock *MockManager) GetPropagator() propagation.TextMapPropagator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPropagator")
	}

	var r0 propagation.TextMapPropagator
	if returnFunc, ok := ret.Get(0).(func() propagation.TextMapPropagator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(propagation.TextMapPropagator)
		}
	}
	return r0
}

// MockManager_GetPropagator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPropagator'
type MockManager_GetPropagator_Call struct {
	*mock.Call
}

// GetPropagator is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetPropagator() *MockManager_GetPropagator_Call {
	return &MockManager_GetPropagator_Call{Call: _e.mock.On("GetPropagator")}
}

func (_c *MockManager_GetPropagator_Call) Run(run func()) *MockManager_GetPropagator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetPropagator_Call) Return(textMapPropagator propagation.TextMapPropagator) *MockManager_GetPropagator_Call {
	_c.Call.Return(textMapPropagator)
	return _c
}

func (_c *MockManager_GetPropagator_Call) RunAndReturn(run func() propagation.TextMapPropagator) *MockManager_GetPropagator_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetLogProvider provides a mock function for the type MockManager
func (_mock *MockManager) GetSetLogProvider() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSetLogProvider")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_GetSetLogProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetLogProvider'
type MockManager_GetSetLogProvider_Call struct {
	*mock.Call
}

// GetSetLogProvider is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetSetLogProvider() *MockManager_GetSetLogProvider_Call {
	return &MockManager_GetSetLogProvider_Call{Call: _e.mock.On("GetSetLogProvider")}
}

func (_c *MockManager_GetSetLogProvider_Call) Run(run func()) *MockManager_GetSetLogProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetSetLogProvider_Call) Return(b bool) *MockManager_GetSetLogProvider_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_GetSetLogProvider_Call) RunAndReturn(run func() bool) *MockManager_GetSetLogProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetShutdownHandler provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownHandler() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownHandler")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_GetShutdownHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownHandler'
type MockManager_GetShutdownHandler_Call struct {
	*mock.Call
}

// GetShutdownHandler is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownHandler() *MockManager_GetShutdownHandler_Call {
	return &MockManager_GetShutdownHandler_Call{Call: _e.mock.On("GetShutdownHandler")}
}

func (_c *MockManager_GetShutdownHandler_Call) Run(run func()) *MockManager_GetShutdownHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) Return(b bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) RunAndReturn(run func() bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(run)
	return _c
}

// GetShutdownTimeout provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockManager_GetShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownTimeout'
type MockManager_GetShutdownTimeout_Call struct {
	*mock.Call
}

// GetShutdownTimeout is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownTimeout() *MockManager_GetShutdownTimeout_Call {
	return &MockManager_GetShutdownTimeout_Call{Call: _e.mock.On("GetShutdownTimeout")}
}

func (_c *MockManager_GetShutdownTimeout_Call) Run(run func()) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) Return(duration time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) RunAndReturn(run func() time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// GetTraceProvider provides a mock function for the type MockManager
func (_mock *MockManager) GetTraceProvider() *trace.TracerProvider {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTraceProvider")
	}

	var r0 *trace.TracerProvider
	if returnFunc, ok := ret.Get(0).(func() *trace.TracerProvider); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trace.TracerProvider)
		}
	}
	return r0
}

// MockManager_GetTraceProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTraceProvider'
type MockManager_GetTraceProvider_Call struct {
	*mock.Call
}

// GetTraceProvider is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetTraceProvider() *MockManager_GetTraceProvider_Call {
	return &MockManager_GetTraceProvider_Call{Call: _e.mock.On("GetTraceProvider")}
}

func (_c *MockManager_GetTraceProvider_Call) Run(run func()) *MockManager_GetTraceProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetTraceProvider_Call) Return(tracerProvider *trace.TracerProvider) *MockManager_GetTraceProvider_Call {
	_c.Call.Return(tracerProvider)
	return _c
}

func (_c *MockManager_GetTraceProvider_Call) RunAndReturn(run func() *trace.TracerProvider) *MockManager_GetTraceProvider_Call {
	_c.Call.Return(run)
	return _c
}

// GetTracer provides a mock function for the type MockManager
func (_mock *MockManager) GetTracer() trace0.Tracer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTracer")
	}

	var r0 trace0.Tracer
	if returnFunc, ok := ret.Get(0).(func() trace0.Tracer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(trace0.Tracer)
		}
	}
	return r0
}

// MockManager_GetTracer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTracer'
type MockManager_GetTracer_Call struct {
	*mock.Call
}

// GetTracer is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetTracer() *MockManager_GetTracer_Call {
	return &MockManager_GetTracer_Call{Call: _e.mock.On("GetTracer")}
}

func (_c *MockManager_GetTracer_Call) Run(run func()) *MockManager_GetTracer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetTracer_Call) Return(tracer trace0.Tracer) *MockManager_GetTracer_Call {
	_c.Call.Return(tracer)
	return _c
}

func (_c *MockManager_GetTracer_Call) RunAndReturn(run func() trace0.Tracer) *MockManager_GetTracer_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockManager
func (_mock *MockManager) Shutdown(ctx context.Context, code int) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockManager_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - code int
func (_e *MockManager_Expecter) Shutdown(ctx interface{}, code interface{}) *MockManager_Shutdown_Call {
	return &MockManager_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx, code)}
}

func (_c *MockManager_Shutdown_Call) Run(run func(ctx context.Context, code int)) *MockManager_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Shutdown_Call) Return(err error) *MockManager_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Shutdown_Call) RunAndReturn(run func(ctx context.Context, code int) error) *MockManager_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
