// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package postgres

import (
	"context"
	"time"

	"github.com/go-gormigrate/gormigrate/v2"
	mock "github.com/stretchr/testify/mock"
	"go.microcore.dev/framework/telemetry"
	"gorm.io/gorm"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Client provides a mock function for the type MockManager
func (_mock *MockManager) Client() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockManager_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type MockManager_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
func (_e *MockManager_Expecter) Client() *MockManager_Client_Call {
	return &MockManager_Client_Call{Call: _e.mock.On("Client")}
}

func (_c *MockManager_Client_Call) Run(run func()) *MockManager_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Client_Call) Return(dB *gorm.DB) *MockManager_Client_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockManager_Client_Call) RunAndReturn(run func() *gorm.DB) *MockManager_Client_Call {
	_c.Call.Return(run)
	return _c
}

// GetShutdownHandler provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownHandler() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownHandler")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockManager_GetShutdownHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownHandler'
type MockManager_GetShutdownHandler_Call struct {
	*mock.Call
}

// GetShutdownHandler is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownHandler() *MockManager_GetShutdownHandler_Call {
	return &MockManager_GetShutdownHandler_Call{Call: _e.mock.On("GetShutdownHandler")}
}

func (_c *MockManager_GetShutdownHandler_Call) Run(run func()) *MockManager_GetShutdownHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) Return(b bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockManager_GetShutdownHandler_Call) RunAndReturn(run func() bool) *MockManager_GetShutdownHandler_Call {
	_c.Call.Return(run)
	return _c
}

// GetShutdownTimeout provides a mock function for the type MockManager
func (_mock *MockManager) GetShutdownTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetShutdownTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockManager_GetShutdownTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShutdownTimeout'
type MockManager_GetShutdownTimeout_Call struct {
	*mock.Call
}

// GetShutdownTimeout is a helper method to define mock.On call
func (_e *MockManager_Expecter) GetShutdownTimeout() *MockManager_GetShutdownTimeout_Call {
	return &MockManager_GetShutdownTimeout_Call{Call: _e.mock.On("GetShutdownTimeout")}
}

func (_c *MockManager_GetShutdownTimeout_Call) Run(run func()) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) Return(duration time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockManager_GetShutdownTimeout_Call) RunAndReturn(run func() time.Duration) *MockManager_GetShutdownTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// Migrate provides a mock function for the type MockManager
func (_mock *MockManager) Migrate(migrations []*gormigrate.Migration, options *gormigrate.Options) error {
	ret := _mock.Called(migrations, options)

	if len(ret) == 0 {
		panic("no return value specified for Migrate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]*gormigrate.Migration, *gormigrate.Options) error); ok {
		r0 = returnFunc(migrations, options)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type MockManager_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
//   - migrations []*gormigrate.Migration
//   - options *gormigrate.Options
func (_e *MockManager_Expecter) Migrate(migrations interface{}, options interface{}) *MockManager_Migrate_Call {
	return &MockManager_Migrate_Call{Call: _e.mock.On("Migrate", migrations, options)}
}

func (_c *MockManager_Migrate_Call) Run(run func(migrations []*gormigrate.Migration, options *gormigrate.Options)) *MockManager_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*gormigrate.Migration
		if args[0] != nil {
			arg0 = args[0].([]*gormigrate.Migration)
		}
		var arg1 *gormigrate.Options
		if args[1] != nil {
			arg1 = args[1].(*gormigrate.Options)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Migrate_Call) Return(err error) *MockManager_Migrate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Migrate_Call) RunAndReturn(run func(migrations []*gormigrate.Migration, options *gormigrate.Options) error) *MockManager_Migrate_Call {
	_c.Call.Return(run)
	return _c
}

// SetClient provides a mock function for the type MockManager
func (_mock *MockManager) SetClient(client *gorm.DB) Manager {
	ret := _mock.Called(client)

	if len(ret) == 0 {
		panic("no return value specified for SetClient")
	}

	var r0 Manager
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) Manager); ok {
		r0 = returnFunc(client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Manager)
		}
	}
	return r0
}

// MockManager_SetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetClient'
type MockManager_SetClient_Call struct {
	*mock.Call
}

// SetClient is a helper method to define mock.On call
//   - client *gorm.DB
func (_e *MockManager_Expecter) SetClient(client interface{}) *MockManager_SetClient_Call {
	return &MockManager_SetClient_Call{Call: _e.mock.On("SetClient", client)}
}

func (_c *MockManager_SetClient_Call) Run(run func(client *gorm.DB)) *MockManager_SetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetClient_Call) Return(manager Manager) *MockManager_SetClient_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockManager_SetClient_Call) RunAndReturn(run func(client *gorm.DB) Manager) *MockManager_SetClient_Call {
	_c.Call.Return(run)
	return _c
}

// SetTelemetryManager provides a mock function for the type MockManager
func (_mock *MockManager) SetTelemetryManager(telemetry1 telemetry.Manager) error {
	ret := _mock.Called(telemetry1)

	if len(ret) == 0 {
		panic("no return value specified for SetTelemetryManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(telemetry.Manager) error); ok {
		r0 = returnFunc(telemetry1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_SetTelemetryManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTelemetryManager'
type MockManager_SetTelemetryManager_Call struct {
	*mock.Call
}

// SetTelemetryManager is a helper method to define mock.On call
//   - telemetry1 telemetry.Manager
func (_e *MockManager_Expecter) SetTelemetryManager(telemetry1 interface{}) *MockManager_SetTelemetryManager_Call {
	return &MockManager_SetTelemetryManager_Call{Call: _e.mock.On("SetTelemetryManager", telemetry1)}
}

func (_c *MockManager_SetTelemetryManager_Call) Run(run func(telemetry1 telemetry.Manager)) *MockManager_SetTelemetryManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 telemetry.Manager
		if args[0] != nil {
			arg0 = args[0].(telemetry.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) Return(err error) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_SetTelemetryManager_Call) RunAndReturn(run func(telemetry1 telemetry.Manager) error) *MockManager_SetTelemetryManager_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockManager
func (_mock *MockManager) Shutdown(ctx context.Context, code int) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockManager_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
//   - code int
func (_e *MockManager_Expecter) Shutdown(ctx interface{}, code interface{}) *MockManager_Shutdown_Call {
	return &MockManager_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx, code)}
}

func (_c *MockManager_Shutdown_Call) Run(run func(ctx context.Context, code int)) *MockManager_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_Shutdown_Call) Return(err error) *MockManager_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Shutdown_Call) RunAndReturn(run func(ctx context.Context, code int) error) *MockManager_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
